[package]
name = "homebrew"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["wxnacy@gmail.com"]

[dependencies]
tabled = "0.17.0"
anyhow = "1.0.95"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
